onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - bigint-buffer
  - bufferutil
  - cpu-features
  - protobufjs
  - secp256k1
  - ssh2
  - unrs-resolver
  - utf-8-validate

overrides:
  foundryanvil-testcontainers-nodejs: link:../../Library/pnpm/global/5/node_modules/foundryanvil-testcontainers-nodejs
