### GET request for reap main account balance
GET {{host}}/v1/reap/balance

> {%
  client.test("Main account balance request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for reap cards
GET {{host}}/v1/reap/cards

> {%
  client.test("Get cards request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for peaq server status
GET {{host}}/v1/peaq/server-status

> {%
  client.test("Get peaq server status request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Wormhole server status
GET {{host}}/v1/wormhole/server-status

> {%
  client.test("Get wormhole server status request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Wormhole network
GET {{host}}/v1/wormhole/network

> {%
  client.test("Get wormhole network request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Wormhole chain context
GET {{host}}/v1/wormhole/chain-context/Solana

> {%
  client.test("Get wormhole chain context successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Ethers server status
GET {{host}}/v1/ethers/server-status

> {%
  client.test("Get ethers server status request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Ethers latest block number
GET {{host}}/v1/ethers/block-number

> {%
  client.test("Get ethers latest block number request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Ethers finalized block
GET {{host}}/v1/ethers/finalized-block

> {%
  client.test("Get ethers finalized block number request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Solana Kit server status
GET {{host}}/v1/solkit/server-status

> {%
  client.test("Get Solana Kit server status request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Solana Kit latest block number
GET {{host}}/v1/solkit/block-number

> {%
  client.test("Get Solana Kit latest block number request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for local users
GET {{host}}/user

> {%
  client.test("Get local users request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

