### GET request for reap main account balance
GET {{host}}/v1/reap/balance

> {%
  client.test("Main account balance request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for reap cards
GET {{host}}/v1/reap/cards

> {%
  client.test("Get cards request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for peaq server status
GET {{host}}/v1/peaq/server-status

> {%
  client.test("Get peaq server status request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Wormhole server status
GET {{host}}/v1/wormhole/server-status

> {%
  client.test("Get wormhole server status request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Wormhole network
GET {{host}}/v1/wormhole/network

> {%
  client.test("Get wormhole network request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for Wormhole chain context
GET {{host}}/v1/wormhole/chain-context/Solana

> {%
  client.test("Get wormhole chain context successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}

### GET request for local users
GET {{host}}/user

> {%
  client.test("Get local users request successful", function() {
    client.assert(response.status === 200, "Status is NOT 200");
  });
%}