### GraphQL request for LatestBlock
GRAPHQL {{host}}/graphql

query {
    getBlockByNumber(blockNumber: 24068107) {
        creationDate,
        blockNumber,
        hash,
        nonce,
        transactionCount
    }
}