### GraphQL request for Block by Number from ethers.js
GRAPHQL {{host}}/graphql

query {
    getBlockByNumber(blockNumber: 24068107) {
        creationDate,
        blockNumber,
        hash,
        nonce,
        transactionCount
    }
}

### GraphQL request for Block by Number from Solana Kit
GRAPHQL {{host}}/graphql

query {
    getSolanaBlockByNumber(blockNumber: "393324959") {
        creationDate,
        blockNumber,
        hash,
        transactionCount
    }
}

