### WebSocket Message to subscribe to ethers.js Latest Blocknumber
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "ethers-subscribe-blocks",
  "data": {
    "client": "vanilla.js",
    "topic": "block-number"
  }
}
=== wait-for-server

### WebSocket Message to subscribe to ethers.js Finalized Blocks
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "ethers-subscribe-blocks",
  "data": {
    "client": "vanilla.js",
    "topic": "finalized-blocks"
  }
}
=== wait-for-server

### WebSocket Message to subscribe to Solana Kit Latest Blocknumber
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "solkit-subscribe-blocks",
  "data": {
    "client": "vanilla.js",
    "topic": "block-number"
  }
}
=== wait-for-server

### WebSocket Message to subscribe to Solana Kit Finalized Blocks
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "solkit-subscribe-blocks",
  "data": {
    "client": "vanilla.js",
    "topic": "finalized-blocks"
  }
}
=== wait-for-server