### WebSocket Message to subscribe to Latest Blocknumber
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "events",
  "data": {
    "client": "vanilla.js",
    "topic": "block-number"
  }
}
=== wait-for-server

### WebSocket Message to subscribe to Finalized Blocks
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "events",
  "data": {
    "client": "vanilla.js",
    "topic": "finalized-blocks"
  }
}
=== wait-for-server