### WebSocket Message to subscribe to Latest Blocknumber
//Subscribe to websocket pipe
WEBSOCKET {{ws}}
Content-Type: application/json // We use it for highlighting

===
{
  "event": "events",
  "data": {
    "client": "vanilla.js",
    "topic": "blocknumber"
  }
}
=== wait-for-server